# Generated by Django 5.1.7 on 2025-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additemsdetails',
            name='cash_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
