# Generated by Django 5.1.7 on 2025-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0002_additemsdetails_cash_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additemsdetails',
            name='items',
        ),
        migrations.AlterField(
            model_name='additemsdetails',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
