# Generated by Django 5.1.7 on 2025-04-27 16:43
from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0004_sellcustomers_stocks_sellsinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellsinvoices',
            name='date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
