# Generated by Django 5.1.7 on 2025-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0005_sellsinvoices_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellsinvoices',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
