# Generated by Django 5.1.7 on 2025-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0006_alter_sellsinvoices_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellsinvoices',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='sellsinvoices',
            name='cash_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellsinvoices',
            name='phone_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellsinvoices',
            name='advance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
