# Generated by Django 5.1.7 on 2025-04-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0007_remove_sellsinvoices_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellsinvoices',
            name='phone_no',
        ),
    ]
