# Generated by Django 5.1.7 on 2025-04-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0008_remove_sellsinvoices_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellsinvoices',
            old_name='sells_customer',
            new_name='customer',
        ),
    ]
